Add SC16IS7XX example
edison-fw/meta-acpi pull request #5
Opened 2018-12-05 15:33 UTC by staroselskii

Add an example of SC16IS7XX on I2C#6 with GPIO#15 as an interrupt source
and clock-frequency set 14745600. For the latter to work correctly the
latest Linux kernel might be needed that adds the ACPI support to the
driver.

PS: the patchset from Andy is not yet rendered on the linux-serial mailing archive. I'll add it soon.

2018-12-05 21:28 UTC, htot commented
What patches that you are refering do we need for this? I am on 7cf4e6bba5 from @andy-shev, does that have all we need?

2018-12-05 21:32 UTC, andy-shev commented
This one:
https://marc.info/?l=linux-serial&m=154401909921404&w=2

2018-12-05 21:33 UTC, andy-shev commented on recipes-bsp/acpi-tables/samples/edison/sc16is7xx.asl
> +                    100000,                 // Fast mode (400 kHz)
400 0r 100 ?

2018-12-05 21:37 UTC, andy-shev requested changes

2018-12-05 21:37 UTC, andy-shev commented on recipes-bsp/acpi-tables/samples/edison/sc16is7xx.asl
> +                    Package () {"clock-frequency", 14745600 },
Keep indentation style (I'm talking about spaces near to closing `}`)

2018-12-05 21:37 UTC, andy-shev commented on recipes-bsp/acpi-tables/samples/edison/sc16is7xx.asl
> +                    100000,                 // Fast mode (400 kHz)
400kHz or 100kHz?
Btw, had it been tested at 400kHz?

2018-12-05 22:26 UTC, staroselskii commented on recipes-bsp/acpi-tables/samples/edison/sc16is7xx.asl
> +                    Package () {"clock-frequency", 14745600 },
Should be fine now.

2018-12-05 22:27 UTC, staroselskii commented on recipes-bsp/acpi-tables/samples/edison/sc16is7xx.asl
> +                    100000,                 // Fast mode (400 kHz)
Wow, that's a silly one. Thanks! I haven't tested it on 400Khz. I can try tomorrow. Do you think that changing speed here is enough for a test?

2018-12-07 13:38 UTC, andy-shev approved these changes

2018-12-07 13:39 UTC, andy-shev commented
While this PR looks now good to me, it would be still nice to test the IP with 400 kHz speed (if it's allowed by its data sheet) and update (later on?) the ASL.

2018-12-07 14:09 UTC, merged

2018-12-07 14:15 UTC, htot commented
Merged, thanks. Further improvements are always welcome.